Luminara-Hub/namada-ecosystem

user-and-dev-tools/testnet/explorers.md, user-and-dev-tools/testnet/rpc.md
Hey Druide!
Filled out everything to the best of my knowledge :), change it around as you see fit!
ZEN ❤
=> Added RPCs and ZENODE explorer

user-and-dev-tools/mainnet/peers.json, user-and-dev-tools/mainnet/rpc.json
Add LiveRaveN RPC endpoint and peer
=> Add LiveRaveN RPC endpoint and peer

user-and-dev-tools/mainnet/rpc.json
=> add Grand Valley's rpc

user-and-dev-tools/mainnet/interfaces.json, user-and-dev-tools/mainnet/masp-indexers.json, user-and-dev-tools/mainnet/namada-indexers.json, user-and-dev-tools/mainnet/peers.json, user-and-dev-tools/mainnet/rpc.json, user-and-dev-tools/mainnet/seeds.json
We're providing baremetal self hhosted RPC, archive RPC, Indexer, MASP-Indexer and namadillo interface
=> Add Citizen Web3 mainnet infra

user-and-dev-tools/mainnet/interfaces.json, user-and-dev-tools/mainnet/masp-indexers.json, user-and-dev-tools/mainnet/namada-indexers.json, user-and-dev-tools/mainnet/peers.json, user-and-dev-tools/mainnet/seeds.json, user-and-dev-tools/mainnet/tooling-and-scripts.json
just added:
- Seed Node
- Update the peer details
- RPC
- Indexer
- MASP-Indexer
- Valley of Namada (VoN)
=> add Grand Valley services

user-and-dev-tools/mainnet/peers.json, user-and-dev-tools/mainnet/rpc.json
=> Add TdrSys contribution

user-and-dev-tools/mainnet/interfaces.json
just hosted my own Namadillo and edited the namadillo tittle to Valley of Namadillo, i think its cooler 😁 . no other changes, only the tittle name. if there's any restrictions about the tittle changes, please tell me 😁
=> add Grand Valley's Namadillo

user-and-dev-tools/mainnet/interfaces.json, user-and-dev-tools/mainnet/masp-indexers.json, user-and-dev-tools/mainnet/namada-indexers.json, user-and-dev-tools/mainnet/peers.json
Add OriginStake Services
- Namada Interface
- Indexer
- MASP Indexer
- RPC/Websocket
- Peers
=> Add OriginStake Services

user-and-dev-tools/mainnet/interfaces.json, user-and-dev-tools/mainnet/masp-indexers.json, user-and-dev-tools/mainnet/namada-indexers.json, user-and-dev-tools/mainnet/peers.json, user-and-dev-tools/mainnet/rpc.json
- interfaces
- masp-indexers
- namada-indexers
- peers
- rpc
=> Add MurphyNode mainnet infra

user-and-dev-tools/mainnet/masp-indexers.json
=> docs: remove my node from masp-indexers.json

user-and-dev-tools/mainnet/peers.json
=> docs: remove my node from peers.json

user-and-dev-tools/testnet/interfaces.json
=> docs: update interfaces.json

user-and-dev-tools/testnet/namada-indexers.json
=> docs: update namada-indexers.json

user-and-dev-tools/testnet/rpc.json
=> docs: update rpc.json

user-and-dev-tools/testnet/peers.json
=> docs: update peers.json

user-and-dev-tools/mainnet/seeds.json
=> docs: update seeds.json

user-and-dev-tools/mainnet/ibc-relayers/namada-osmosis-1.json
=> Add TdrSys osmosis relayer

user-and-dev-tools/mainnet/interfaces.json, user-and-dev-tools/mainnet/tooling-and-scripts.json, user-and-dev-tools/testnet/housefire/tooling-and-scripts.json
added team/contributor name for `Hadesguard` and `Sproutstake`
=> docs: interfaces.json mainnet

user-and-dev-tools/testnet/housefire/namada-indexers.json
- **endpoint:** `https://housefire.rpc.papadritta.com/indexer/` 
- **version of Indexer:** `v2.3.0` for `Housefire`
=> Update [namada-indexers] json

user-and-dev-tools/mainnet/ibc-relayers/namada-cosmoshub-4.json, user-and-dev-tools/mainnet/ibc-relayers/namada-osmosis-1.json, user-and-dev-tools/mainnet/ibc-relayers/namada-stride-1.json
Mainnet cosmos , osmosis , stride
=> Add Inter Blockchain Services relayers infos

user-and-dev-tools/testnet/housefire/interfaces.json
Namadillo interface `v1.16.0` for `Housefire`  with Indexer `v2.1.0` and RPC Server, hosted on a bare-metal server and securely exposed via `Nginx-proxied SSL endpoints`.
>Built Namadillo UI (v1.16.0) with WebAssembly dependencies.
**Configured and integrated:**
- Indexer v2.1.0 at https://housefire.indexer.papadritta.com.
- RPC Server at https://housefire.rpc.papadritta.com.
- Deployed the application on a bare-metal server with an Nginx reverse proxy.
- Served the UI via SSL at https://housefire.ui.papadritta.com.
- Updated config.toml to use the correct Indexer and RPC URLs.
- Web Interface: `https://housefire.ui.papadritta.com`
- Indexer API: `https://housefire.indexer.papadritta.com`
- RPC Server: `https://housefire.rpc.papadritta.com`
- Hosting: `Bare-metal` server with `Nginx` as a …
=> Add [Interface Build on Namadillo v1.16.0]

user-and-dev-tools/mainnet/ibc-relayers/namada-neutron-1.json, user-and-dev-tools/mainnet/ibc-relayers/namada-noble-1.json, user-and-dev-tools/mainnet/ibc-relayers/namada-nyx.json, user-and-dev-tools/mainnet/ibc-relayers/namada-penumbra-1.json
Heya! Added my new IBC relayer details. ~~Will soon also add Penumbra once I set that up.~~
**EDIT:** Also added Penumbra ;)!
=> Updated anodeofzen IBC relayer details

user-and-dev-tools/mainnet/ibc-relayers/namada-neutron-1.json, user-and-dev-tools/mainnet/ibc-relayers/namada-noble-1.json
=> Add IBS relayer infos

user-and-dev-tools/mainnet/masp-indexers.json, user-and-dev-tools/mainnet/namada-indexers.json, user-and-dev-tools/mainnet/rpc.json, user-and-dev-tools/mainnet/seeds.json
indexer, masp-indexer, rpc and seed
=> add NODERS contributions

user-and-dev-tools/testnet/housefire/interfaces.json, user-and-dev-tools/testnet/housefire/masp-indexers.json, user-and-dev-tools/testnet/housefire/namada-indexers.json, user-and-dev-tools/testnet/housefire/rpc.json
**Add  namada-indexer, masp - Indexer**: 
- Indexer API URL: https://alpaca.cc0d3e0c033be-indexer.laliola.com
- Masp - Indexer API URL: https://alpaca.cc0d3e0c033be-masp-indexer.laliola.com
- RPC Address: https://alpaca.cc0d3e0c033be-rpc.laliola.com
- Namadillo Interface URL: https://alpaca.cc0d3e0c033be-ui.laliola.com
=> Update [testnet/housefire: Add: Indexer, Masp-Indexer, RPC, Namadillo]

_luminara-homebase/services_health_config.json
=> chore: bump namadillo version to 1.28.3

user-and-dev-tools/testnet/housefire/ibc-relayers/housefire-cosmoshub-4.json, user-and-dev-tools/testnet/housefire/ibc-relayers/housefire-osmosis-test-5.json
cosmoshub-4 , osmo-test-5 and grand-1
=> Update IBC Paths testnet
